sudo: false
language: node_js
node_js:
- '10'
notifications:
  email: false
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- yarn run build
- yarn run test-ci
- yarn run lint
after_script: greenkeeper-lockfile-upload
deploy:
  provider: surge
  project: ./build/
  domain: truthordare.surge.sh
  skip_cleanup: true
