sudo: false
language: node_js
node_js:
- '10'
notifications:
  email: false
before_install:
# package-lock.json was introduced in npm@5
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
- npm install -g greenkeeper-lockfile
install: npm install
before_script: greenkeeper-lockfile-update
script:
- npm run build
- npm run test-ci
- npm run lint
after_script: greenkeeper-lockfile-upload
deploy:
  provider: surge
  project: ./build/
  domain: truthordare.surge.sh
  skip_cleanup: true
