const constants = {
    IMPORT_QUESTIONS: 'IMPORT_QUESTIONS',
    ADD_QUESTION: 'ADD_QUESTION',
    DELETE_QUESTION: 'DELETE_QUESTION',
    CLEAR_QUESTIONS: 'CLEAR_QUESTIONS'
};

export default constants;
