const constants = {
    IMPORT_QUESTIONS: 'IMPORT_QUESTIONS',
    ADD_TRUTH: 'ADD_TRUTH',
    ADD_DARE: 'ADD_DARE',
    DELETE_TRUTH: 'DELETE_TRUTH',
    DELETE_DARE: 'DELETE_DARE',
    IMPORT_TRUTHS: 'IMPORT_TRUTHS',
    IMPORT_DARES: 'IMPORT_DARES',
    CLEAR_TRUTHS: 'CLEAR_TRUTHS',
    CLEAR_DARES: 'CLEAR_DARES'
};

export default constants;
